export const teamMembers = [
  {
    name: 'O.P. Singh',
    role: 'Emeritus Chairman',
    image: '/images/team/op-singh.jpg',
    group: 'Core Team',
  },
  {
    name: 'Dr. P.K. Singh',
    role: 'Group C.E.O.',
    image: '/images/team/pk-singh.jpg',
    group: 'Core Team',
  },
  {
    name: 'Debdutta Ghosh',
    role: 'Group CHRO',
    image: '/images/team/debdutta-ghosh.jpeg',
    group: 'Core Team',
  },
  {
    name: 'Shruti Singh',
    role: 'Board Advisor - LSCM',
    image: '/images/team/shruti-singh.jpg',
    group: 'Core Team',
  },
  {
    name: 'Adv. Dr. K.R. Madhar (I.R.S. Retd.)',
    role: 'Delhi High Court',
    image: '/images/team/kr-madhar.jpg',
    group: 'Core Team',
  },
  {
    name: 'Adv. Kailash Chand',
    role: 'Former Assistant Commissioner of Customs & GST (retd.)',
    image: '/images/team/kailash-chand.jpg',
    group: 'Core Team',
  },
  {
    name: 'Adv. Gaurav Bhardwaj',
    nameSuffix: '(Supreme Court of India)',
    role: 'Head Advisory Board, Legal',
    image: '/images/team/gaurav-bhardwaj.jpg',
    group: 'Core Team',
  },
  {
    name: 'Ananya Singh',
    role: 'Strategist, Legal',
    image: '/images/team/ananya-singh.jpeg',
    group: 'Core Team',
  },
  {
    name: 'Dr. Tanu Manocha',
    role: 'Strategic Board Advisor, Operations',
    image: '/images/team/tanu-manocha.jpeg',
    group: 'Core Team',
  },
  {
    name: 'Dr. Vijay Prakash Sharma',
    role: 'Group Advisor- Business Strategy',
    image: '/images/team/vijay-prakash-sharma.jpeg',
    group: 'Core Team',
  },
  {
    name: 'Abhishek Chaudhary',
    role: 'Team Lead - Tech',
    image: '/images/businesses/enterprise/team/abhishek.png',
    group: 'Enterprise Team',
  },
  {
    name: 'Moazzam Ahmed Siddiqui',
    role: 'Team Lead - AI & ML',
    image: '/images/businesses/enterprise/team/moazzam.png',
    group: 'Enterprise Team',
  },
  {
    name: 'Ujjwal Rawat',
    role: 'Team Lead - Full Stack',
    image: '/images/businesses/enterprise/team/ujjwal.png',
    group: 'Enterprise Team',
  },
  {
    name: 'Ishu Dagar',
    role: 'Team Lead - Digital Marketing',
    image: '/images/businesses/enterprise/team/ishu.png',
    group: 'Enterprise Team',
  },
  {
    name: 'Adarsh Kumar Singh',
    role: 'Team Lead - HR',
    image: '/images/businesses/enterprise/team/adarsh.jpeg',
    group: 'Enterprise Team',
  },
]
